name: Web app sync action

on:
  workflow_dispatch:
  push:
    branches:
      - Azure-config

permissions:
  id-token: write
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
            app-name: 'carlos-dominio-app-01'
            slot-name: 'production'
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            package: '.'
